force-app/main/default/objects/Aeropuerto__c/Aeropuerto__c.object-meta.xml
<CustomObject>
    <description>es una locación física que está acondicionado
para recibir y despachar vuelos en diferentes ciudades</description>
    <label>Aeropuerto</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Codigo del aeropueto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aeropuertos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aeropuerto__c/fields/Codigo_IATA__c.field-meta.xml
<CustomField>
    <fullName>Codigo_IATA__c</fullName>
    <description>Código IATA con el que se Identifica cada aeropuerto</description>
    <label>Codigo IATA</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Aeropuerto__c/fields/Cuidad__c.field-meta.xml
<CustomField>
    <fullName>Cuidad__c</fullName>
    <label>Cuidad</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Pais__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Albacete</fullName>
            </value>
            <value>
                <fullName>Ámsterdam</fullName>
            </value>
            <value>
                <fullName>Antofagasta</fullName>
            </value>
            <value>
                <fullName>Arica</fullName>
            </value>
            <value>
                <fullName>Astaná</fullName>
            </value>
            <value>
                <fullName>Asunción</fullName>
            </value>
            <value>
                <fullName>Atenas</fullName>
            </value>
            <value>
                <fullName>Bagram</fullName>
            </value>
            <value>
                <fullName>Bahia</fullName>
            </value>
            <value>
                <fullName>Balmaceda</fullName>
            </value>
            <value>
                <fullName>Bamiyán</fullName>
            </value>
            <value>
                <fullName>Barcelona</fullName>
            </value>
            <value>
                <fullName>Basilea, Mulhouse, Friburgo</fullName>
            </value>
            <value>
                <fullName>Beja</fullName>
            </value>
            <value>
                <fullName>Berlín</fullName>
            </value>
            <value>
                <fullName>Bilbao</fullName>
            </value>
            <value>
                <fullName>Bogotá</fullName>
            </value>
            <value>
                <fullName>Budapest</fullName>
            </value>
            <value>
                <fullName>Buenos Aires</fullName>
            </value>
            <value>
                <fullName>Burdeos</fullName>
            </value>
            <value>
                <fullName>Cali</fullName>
            </value>
            <value>
                <fullName>Caracas</fullName>
            </value>
            <value>
                <fullName>Casablanca</fullName>
            </value>
            <value>
                <fullName>Castellon</fullName>
            </value>
            <value>
                <fullName>Cayo Coco</fullName>
            </value>
            <value>
                <fullName>Chicago</fullName>
            </value>
            <value>
                <fullName>Chihuahua</fullName>
            </value>
            <value>
                <fullName>Ciudad de Corrientes</fullName>
            </value>
            <value>
                <fullName>Ciudad de Formosa</fullName>
            </value>
            <value>
                <fullName>Ciudad de Guatemala</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Aeropuerto__c/fields/Nombre_del_Aeropuerto__c.field-meta.xml
<CustomField>
    <fullName>Nombre_del_Aeropuerto__c</fullName>
    <description>Nombre del aeropuerto del vuelo buscado</description>
    <label>Nombre del Aeropuerto</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Aeropuerto__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <description>Países de los aeropuertos</description>
    <label>Pais</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afganistán</fullName>
            </value>
            <value>
                <fullName>Alemania</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Arabia Saudita</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bangladés</fullName>
            </value>
            <value>
                <fullName>Bélgica</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Brasil</fullName>
            </value>
            <value>
                <fullName>Brasil</fullName>
            </value>
            <value>
                <fullName>Canadá</fullName>
            </value>
            <value>
                <fullName>Catar</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Chipre</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Corea del Sur</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Croacia</fullName>
            </value>
            <value>
                <fullName>Cuba</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>Emiratos Árabes Unidos</fullName>
            </value>
            <value>
                <fullName>España</fullName>
            </value>
            <value>
                <fullName>Estados Unidos</fullName>
            </value>
            <value>
                <fullName>Finlandia</fullName>
            </value>
            <value>
                <fullName>Francia</fullName>
            </value>
            <value>
                <fullName>Grecia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Avion__c/Avion__c.object-meta.xml
<CustomObject>
    <description>Un avión es un artefacto de transporte de pasajeros o carga.
Si el avión es de tipo carga no se debe admitir número de
pasajeros.</description>
    <label>Avion</label>
    <nameField>
        <displayFormat>AV-{00000}</displayFormat>
        <label>Numero de Avion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aviones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Avion__c/fields/Aeronave__c.field-meta.xml
<CustomField>
    <fullName>Aeronave__c</fullName>
    <description>Tipo de avión que viajara, si es comercial o de carga</description>
    <label>Aeronave</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/N_mero_de_pasajeros_clase_negocios__c.field-meta.xml
<CustomField>
    <fullName>N_mero_de_pasajeros_clase_negocios__c</fullName>
    <description>Número de pasajeros que viaja en la clase negocios</description>
    <label>Número de pasajeros clase negocios</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/N_mero_de_pasajeros_clase_Turista__c.field-meta.xml
<CustomField>
    <fullName>N_mero_de_pasajeros_clase_Turista__c</fullName>
    <description>es el Numero de pasajeros que viaja en clase turista</description>
    <label>Número de pasajeros clase Turista</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/descuentoRemateBatchTest.cls
@istest
public with sharing class descuentoRemateBatchTest {
    
    @TestSetup
    static void makeData(){
        List<Contact> lista = new List<Contact>();
        for(Integer i = 0; i < 2; i++){
            Contact cto = new Contact(FirstName = 'señor', LastName = 'pruebas', 
                                        Tipo_de_Indetificacion__c = 'Cédula de Extranjería',
                                        N_mero_de_indetificacion__c = String.valueof(i));
            lista.add(cto);
        }
        insert lista;
        String id = lista[0].Id;

        Avion__c avion = new Avion__c(Aeronave__c  = 'Airbus A330', N_mero_de_pasajeros_clase_negocios__c = 30, 
        N_mero_de_pasajeros_clase_Turista__c = 222);
        insert avion;

       
        List<Aeropuerto__c> aeropuertos = new List<Aeropuerto__c>();
        for (Integer i = 0; i<2 ; i++) {
            Aeropuerto__c aeropuerto = new Aeropuerto__c(Nombre_del_Aeropuerto__c = 'aero pruebas'+i, Pais__c = 'Chile', Codigo_IATA__c = 'BBA', Cuidad__c = 'Balmaceda');
            aeropuertos.add(aeropuerto);
        }
        insert aeropuertos;
        String idAvion = avion.Id;
        List<Product2> Vuelos = new List<Product2>();
        for(Integer i = 0; i < 2; i++){
            Product2 vuelo = new Product2(Name = 'AE-2552', 
                                        Fecha_y_hora_de_partida__c = Datetime.now().addHours(10), Fecha_y_hora_estimada_de_llegada__c = Datetime.now().addHours(12),
                                        Avion__c = idAvion, Aeropuerto_de_partida__c = aeropuertos[0].Id,
                                        Aeropuerto_de_Llegada__c = aeropuertos[1].Id );
            Vuelos.add(vuelo);
        }
        insert Vuelos;
        String idV = Vuelos[0].Id;
        Id idEstandar = Test.getStandardPricebookId();
        //Insertar entrada de precios estandar
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = idEstandar, Product2Id = idV,
                                                          UnitPrice = 10000, IsActive = true,
                                                          descuento_35__c =  true,
                                                          descuento_50__c = false);
        insert standardPrice;
        
        Pricebook2 negocios = new Pricebook2(Name = 'Clase Negocios', IsActive = true);
        insert negocios;

        
        Pricebook2 turista = new Pricebook2(Name = 'clase turista', IsActive = true);
        insert turista;
        
        PricebookEntry entrada = new PricebookEntry(Pricebook2Id = turista.id, Product2Id = idV, 
                                                    UnitPrice = 20000, isActive = true,
                                                    descuento_35__c =  false,
                                                    Descuento_50__c = false);
        insert entrada;
        
        
        Opportunity res = new Opportunity(Name = 'reserva de prueba', Titular_de_la_Reserva__c = id, 
                                        CloseDate = System.today(), StageName = 'Pre-venta', 
                                        Pricebook2Id = turista.Id);
        Insert res;
    }

    @isTest
    static void pruebaDescuentoMartes(){
        Test.startTest();
        DescuentoRemateSchedulable prueba = new DescuentoRemateSchedulable();
        String sch = '1 0 0 ? * * *';
        String jobID = System.schedule('DescuentoRemateSchedulable', sch, prueba);
        descuentoRemateBatch descuento = new descuentoRemateBatch();
        ID batchprocessid = Database.executeBatch(descuento);
        Test.stopTest();
        
        List<PricebookEntry> entradaConDescuento = [SELECT Id 
                                FROM PricebookEntry 
                                WHERE Descuento_50__c = true];
        System.assertEquals(2, entradaConDescuento.size());
    }

}