force-app/main/default/objects/Avion__c/Avion__c.object-meta.xml
<CustomObject>
    <description>Un avión es un artefacto de transporte de pasajeros o carga.
Si el avión es de tipo carga no se debe admitir número de
pasajeros.</description>
    <label>Avion</label>
    <nameField>
        <displayFormat>AV-{00000}</displayFormat>
        <label>Numero de Avion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aviones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Avion__c/fields/Aeronave__c.field-meta.xml
<CustomField>
    <fullName>Aeronave__c</fullName>
    <description>Tipo de avión que viajara, si es comercial o de carga</description>
    <label>Aeronave</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/N_mero_de_pasajeros_clase_negocios__c.field-meta.xml
<CustomField>
    <fullName>N_mero_de_pasajeros_clase_negocios__c</fullName>
    <description>Número de pasajeros que viaja en la clase negocios</description>
    <label>Número de pasajeros clase negocios</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/N_mero_de_pasajeros_clase_Turista__c.field-meta.xml
<CustomField>
    <fullName>N_mero_de_pasajeros_clase_Turista__c</fullName>
    <description>es el Numero de pasajeros que viaja en clase turista</description>
    <label>Número de pasajeros clase Turista</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/vueloXcontacto__c/vueloXcontacto__c.object-meta.xml
<CustomObject>
    <label>vueloXcontacto</label>
    <nameField>
        <displayFormat>AUX-{0000}</displayFormat>
        <label>Codigo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VueloXcontactos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/vueloXcontacto__c/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <label>Contacto</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VueloXcontactos</relationshipLabel>
    <relationshipName>VueloXcontactos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/vueloXcontacto__c/fields/Vuelo__c.field-meta.xml
<CustomField>
    <fullName>Vuelo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vuelo</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>VueloXcontactos</relationshipLabel>
    <relationshipName>VueloXcontactos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/tripulacionRequeridaTest.cls
@isTest
public with sharing class tripulacionRequeridaTest {
   
    @TestSetup
    static void makeData(){
        avion__c avion = new avion__c(N_mero_de_pasajeros_clase_negocios__c = 0, N_mero_de_pasajeros_clase_Turista__c = 150, Aeronave__c = 'Airbus de pruebas');
        insert avion;
        
        avion__c newAvion = [SELECT Id FROM Avion__c LIMIT 1];

        product2 vuelo = new Product2(Name = 'AV-0001', Avion__c = newAvion.Id , Fecha_y_hora_de_partida__c = DateTime.now()+8/7,
                                    Fecha_y_hora_estimada_de_llegada__c = (DateTime.now()+8/7).addHours(1), IsActive = true, Estado__c = 'En Venta');
        insert vuelo;

        Contact auxiliar1 = new Contact(firstName='señor', lastName='pruebas', RecordTypeId='0128a000000Gu8zAAC',
                                        N_mero_de_Pasaporte__c='12312345', Nacionalidad__c='colombiano',
                                        Birthdate=Date.newInstance(2004,03,01));
        insert auxiliar1;

        List<Contact> contactos = new List<Contact>();
        for(integer i = 0; i < 1;i++){
            Contact auxiliar2 = new Contact(firstName='señor'+i, lastName='pruebas'+i, RecordTypeId='0128a000000Gu8zAAC',
                                        N_mero_de_Pasaporte__c='1231234522'+i, Nacionalidad__c='argentino',
                                        Birthdate=Date.newInstance(1990,05,09));
            contactos.add(auxiliar2);
        }
        insert contactos;

        product2 vueloTest = [SELECT Id FROM Product2 LIMIT 1];
        Contact auxTest = [SELECT Id FROM Contact LIMIT 1];

        vueloXcontacto__c junction = new vueloXcontacto__c(Contacto__c = auxTest.Id, Vuelo__c = vueloTest.Id);
        insert junction;
        
    }

    @isTest
    private static void getVuelo(){
        List<TripulacionRequerida.vuelo> vuelos = TripulacionRequerida.getVuelosPendientes();
        system.assertEquals(1, vuelos.size());
    }

    @isTest
    private static void errorGetVuelo(){
        avion__c fakeAvion = [SELECT Id FROM avion__c LIMIT 1];
        delete fakeAvion;
        
        try {
            List<TripulacionRequerida.vuelo> vuelos = TripulacionRequerida.getVuelosPendientes();
        }
        catch (Exception e) {
            system.assert(e.getMessage().contains('Script-thrown exception'));
        }
        
    }

    @isTest
    private static void auxiliares(){
        
        Product2 vuelos = [SELECT Id FROM product2 LIMIT 1];
        
        List<TripulacionRequerida.opcion> auxiliares = TripulacionRequerida.getAuxiliares(vuelos.id);
        system.assertEquals(3, auxiliares.size());
    }

    @isTest
    private static void fakeAuxiliar(){
        
        List<TripulacionRequerida.opcion> auxiliares = TripulacionRequerida.getAuxiliares('4251aad');
    }

    @isTest
    private static void getAuxiliar(){
        Product2 vuelos = [SELECT Id FROM product2 LIMIT 1];
 
        List<Contact> axuliar1 = [SELECT Id FROM Contact];
        List<string> getId = new List<string>();
        for(Contact a: axuliar1){
            getId.add(a.Id);
        }
        TripulacionRequerida.saveAuxiliares(getId,vuelos.id);

        List<TripulacionRequerida.opcion> auxiliares = TripulacionRequerida.getAuxiliares(vuelos.id);
        system.assertEquals(4, auxiliares.size());
    }
}